
  - name: playbook for debug
    hosts: all
    vars:
      URL: www.IBN Technologies.com
    tasks:
        - name: print hello world
          debug:
            msg: "Please visit {{ URL }}"
        - name: print hello world
          debug:
            msg: "Please visit {{ URL }}"
        - name: print hello world
          debug:
            msg: "Please visit {{ URL }}"
            vars:
              URL: local.IBN Technologies.com
