
  - name: playbook for prompt
    hosts: all
    vars: 
      URL: "www.IBNTechnologies.com"
    vars-prompt:
      - name: URL
        prompt: "www.CloudIBN.com"
        private: false
    tasks:
          - name: print hello world
            debug:
             msg: "Please visit {{ URL }}
